// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://shxncrzawwosgupunuue.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNoeG5jcnphd3dvc2d1cHVudXVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MjE5NDUsImV4cCI6MjA2Mzk5Nzk0NX0.YmrNMdYFVMwcm1GgLOQWkMu0VKLDNeF9ZntRFCOFP7s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);